### ISSUE TITLE
lab broken by Chrome

### ISSUE THREAD

**Issue by ayerik** [learn-co-curriculum/konami-code-lab#10]
This lab needs to be reworked to not use an alert, or code needs to be added to the index-test.js file.  Google has disabled alert within an iframe unless the allow modal property has been enabled, per the MDN

https://developer.mozilla.org/en-US/docs/Web/API/Window/alert, under Notes -- "Starting with Chrome 46.0 this method is blocked inside an <iframe> unless its sandbox attribute has the value allow-modal."

**Comment by itzsaga** [comment]
Just ran into this too.

**Comment by gj** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 🙂
