### ISSUE TITLE
e.location

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/konami-code-lab#13]
Using Chrome version 57.0.2987.133

Inside a function `onKeydownEvent(e)`, `e.which` and `e.detail` both evaluate to `0` for every key, but `e.location` gives the correct key code.

**Comment by gj** [comment]
Hi @mdo5004 !

In Chrome 59.0.3071.115, `.which` provides the correct key code. `.detail` and `.location` both evaluate to `0`. 🤷‍♂️

I've added a bit about `e.location` to the hint.

Thanks!
