### ISSUE TITLE
Passed the test with wrong code

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/konami-code-lab#14]
Was able to pass the test with this wrong code:
even on the last index we still i++, the code.length - 1 does not account for the fact that at the last index [9]  we still need to see what the user types in. Because it does not it alerts early without the last code being typed

  if (index === code.length - 1) {
          alert("YOU DID IT!")
          index = 0;

**Comment by cassaram09** [comment]
I worked with a student today who pointed this out. Incrementing index should happen _after_ the `(index === code.length - 1)` condition. 
```
function init() {
  var index = 0

  document.body.addEventListener('keydown', function(e) {
    const key = parseInt(e.which || e.detail)

    if (code[index] === key) {
      if (index === code.length - 1) {
        alert('hurray!')
        index = 0
      }
      index++ // increment index here 
    } else {
      index = 0
    }
  })
}
```

@aturkewi

**Comment by gj** [comment]
Hi @pigusan and @cassaram09 !

I've updated the example code in README.md and the solution code. Does everything look good now?

Thanks!

**Comment by bmcilhenny** [comment]
It does,

thanks!

Brendan

**Comment by gj** [comment]
Awesome! Thanks again @pigusan 🎉
