### ISSUE TITLE
Question regarding code

### ISSUE THREAD

**Issue by sparklie3** [learn-co-curriculum/konami-code-lab#2]
I passed the test for the konami code, but I noticed that the test can be passed with 

`if (index === code.length - 1) {
-        alert("YOU DID IT!")
-        index = 0`

the code.length - 1 didn't make any sense to me, but it allows you to pass the test.  Shouldn't it only allow you to pass the test when you've executed ever part of the code? If you run the above, you get the alert YOU DID IT after pressing "B" and not finishing with A. 

You'll see how people have passed the test:

Example: https://github.com/braden337/konami-code-lab-js-intro-000/commit/42aa2de784f43453cc5c420310850c1885e2d080

You can look at my github and see that I removed the -1 from the if statement.

**Comment by AnnJohn** [comment]
hi @sparklie3 could you use Ask a Question for this? That way someone from our team will be able to help you out and explain anything you need clarification on. And if there is an error with the lab, then they'll raise an issue on it. Thanks!
