### ISSUE TITLE
e.which - usage of deprecated variable causes tests to fail

### ISSUE THREAD

**Issue by developerjigr** [learn-co-curriculum/konami-code-lab#21]
var key = parseInt(e.which || e.detail) does not pass the test for showing the alert as e.which is deprecatted.

It would probably be more friendly towards users who are learning if the content was updated to show the use of e.key instead to avoid confusion on where the problem is coming from.  

var key = parseInt(e.key || e.detail);

**Comment by DanielSeehausen** [comment]
@rrcobb the just merged pr addressed this correct?
