### ISSUE TITLE
Browser Sync Issue

### ISSUE THREAD

**Issue by btmccollum** [learn-co-curriculum/konami-code-lab#26]
All tests pass but the alert piece is not functioning when called. The DOM also returns an error around browser sync and the IDE does the same when loading with the following. Additionally there does not appear to be anything in the indexTest.js file to report the results of the test back after looking through with a technical coach:

In the IDE:

[1/4] Resolving packages...
warning learn-browser > sinon > formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
warning learn-browser > browser-sync > browser-sync-ui > weinre > express@2.5.11: express 2.x series is deprecated
warning learn-browser > browser-sync > browser-sync-ui > weinre > express > connect@1.9.2: connect 1.x series is deprecated
warning learn-browser > browser-sync > browser-sync-ui > weinre > express > connect > formidable@1.0.17: Old versions of Formidable are not compatible with thecurrent Node.js; Upgrade to 1.2.0 or later

DOM error on load on the test page:

Uncaught ReferenceError: ___browserSync___ is not defined
    at l (learnBrowser.min.js:1)
    at Runner.mocha.run.on.on (learnBrowser.min.js:1)
    at Runner.EventEmitter.emit (mocha.js:389)
    at mocha.js:5317
    at mocha.js:5165
    at next (mocha.js:4800)
    at mocha.js:4844
    at timeslice (mocha.js:82)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
