### ISSUE TITLE
Error Window never popped up

### ISSUE THREAD

**Issue by junglerhino37** [learn-co-curriculum/konami-code-lab#27]
Code was correct, verified by testing with posted solution branch, error window pops up in init file but not in the event handler. Using Chrome.

**Comment by d-d-d-dalia** [comment]
Another student today with the same issue.

**Comment by morgvanny** [comment]
I believe the test intercepts the alert - essentially disabling it from a UI standpoint - but is able to see if it _should_ work. To get the actual satisfaction of seeing the alert, I believe you have to comment out the test script in the index.html to keep that from running, and then load up that page in chrome. Keeping this open in case there's a way to change the test file to stop breaking alerts. I'm unaware if there is.

**Comment by Al3nMicL** [comment]
please @rrcobb or @DanielSeehausen update the README.md to mention that the test file intercepts window alerts. It's frustrating trying to figure this out while debugging your code in browser (Especially when you are trying to trigger expected behavior).

Thanks @morgvanny for mentioning this!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
