### ISSUE TITLE
I'm not able to fork this lab 

### ISSUE THREAD

**Issue by marissaorea** [learn-co-curriculum/konami-code-lab#28]
<img width="1440" alt="screen shot 2018-10-12 at 1 15 18 pm" src="https://user-images.githubusercontent.com/22510881/46883730-f20cca80-ce20-11e8-9762-f95cab5448a5.png">

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
