### ISSUE TITLE
Solution isn't quite right

### ISSUE THREAD

**Issue by johnshelb** [learn-co-curriculum/konami-code-lab#5]
The solution provided for this lab has an error:
the final condition before the 'hurray!' alert is triggered if the index === code.length -1, but,
since index is incremented before that check, it will trigger the reward message when the 2nd to last keystroke is made instead of waiting for the last.

Suggested fix:
change:
 if (index === code.length - 1) 
to:
 if (index === code.length)

**Comment by hannah-jj** [comment]
agree with this comment.

**Comment by ghost** [comment]
I agree. Noticed the same problem.

**Comment by gj** [comment]
Thanks @johnshelb !
