### ISSUE TITLE
Bug in solution for Konami code lab?

### ISSUE THREAD

**Issue by LeonsEventHorizons** [learn-co-curriculum/konami-code-lab#8]
The code below is my code for this lab and it works as it should when I run it on my personal web server using WAMP. However, it doesn't past the Learn test. The thing is when I run the Learn sample solution on my WAMP server the "alert" box appears when you press the second last letter - "B". Shouldn't the alert box be showing up on the last letter "A" instead?

// This is my code works with WAMP but not for the Learn test. 
        const code = [38, 38, 40, 40, 37, 39, 37, 39, 66, 65]

        init();

        function init() {

            var index = 0;
            const getElement = document.querySelector('body');

            getElement.addEventListener('keydown', function(e) {
                if (code[index] === e.which || code[index] === e.detail) {
                    index++;

                    if (index === code.length) {
                        alert("CHEAT EXECUTED!!");
                        index = 0;
                    }
                } else {
                    index = 0;
                }
            })
        }

**Comment by gj** [comment]
Thanks @LeonsEventHorizons !
